export const ADD_OFFBEAT_REQUEST = 'ADD_OFFBEAT_REQUEST'
export const ADD_OFFBEAT_SUCCESS = 'ADD_OFFBEAT_SUCCESS'
export const ADD_OFFBEAT_FAIL = 'ADD_OFFBEAT_FAIL'

export const GET_OFFBEAT_REQUEST = 'GET_OFFBEAT_REQUEST'
export const GET_OFFBEAT_SUCCESS = 'GET_OFFBEAT_SUCCESS'
export const GET_OFFBEAT_FAIL = 'GET_OFFBEAT_FAIL'