export const GET_PLAN_REQUEST = 'GET_PLAN_REQUEST'
export const GET_PLAN_SUCCESS = 'GET_PLAN_SUCCESS'
export const GET_PLAN_FAIL = 'GET_PLAN_FAIL'

export const ADD_PLAN_REQUEST = 'ADD_PLAN_REQUEST'
export const ADD_PLAN_SUCCESS = 'ADD_PLAN_SUCCESS'
export const ADD_PLAN_FAIL = 'ADD_PLAN_FAIL'