export const GET_ALL_SPOT_REQUEST = 'GET_ALL_SPOT_REQUEST'
export const GET_ALL_SPOT_SUCCESS = 'GET_ALL_SPOT_SUCCESS'
export const GET_ALL_SPOT_FAIL = 'GET_ALL_SPOT_FAIL'

export const GET_SINGLE_SPOT_REQUEST = 'GET_SINGLE_SPOT_REQUEST'
export const GET_SINGLE_SPOT_SUCCESS = 'GET_SINGLE_SPOT_SUCCESS'
export const GET_SINGLE_SPOT_FAIL = 'GET_SINGLE_SPOT_FAIL'