export const GET_ALL_SUBPLACES_REQUEST = 'GET_ALL_SUBPLACES_REQUEST'
export const GET_ALL_SUBPLACES_SUCCESS = 'GET_ALL_SUBPLACES_SUCCESS'
export const GET_ALL_SUBPLACES_FAIL = 'GET_ALL_SUBPLACES_FAIL'

export const GET_SINGLE_SUBPLACE_REQUEST = 'GET_SINGLE_SUBPLACE_REQUEST'
export const GET_SINGLE_SUBPLACE_SUCCESS = 'GET_SINGLE_SUBPLACE_SUCCESS'
export const GET_SINGLE_SUBPLACE_FAIL = 'GET_SINGLE_SUBPLACE_FAIL'